# Site settings
title: Font Storage For smcleod.net
description: "A blog about Font Storage For smcleod.net ..."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://fonts.smcleod.net"

# User settings
username: s_mcleod
user_title: Font Storage For smcleod.net - FrontEnd
email: not@telling.com
twitter_username: "@s_mcleod"
github_username: sammcj
# gplus_username:  loremipsum
# disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: smcleod.net
    url: https://smcleod.net
#   - title: series
#     url: /series
#   - title: tags
#     url: /tags
#   - title: About me
#     url: /about
# # projects in header index
# projects:
#   - name: asciilang
#     url: https://github.com/victorvoid/asciilang
#   - name: vim-frontend
#     url: https://github.com/victorvoid/vim-frontend
#   - name: generator-capybara
#     url: https://github.com/victorvoid/generator-capybara
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
